networks:
  etl_bridge:
    driver: bridge

services:
  zookeeper:
    extends:
      file: containers/kafka.yaml
      service: zookeeper
    networks:
      - etl_bridge
    profiles: [infrastracture]
    user: root

  kafka:
    extends:
      file: containers/kafka.yaml
      service: kafka
    networks:
      - etl_bridge
    profiles: [infrastracture]
    user: root

  postgres:
    extends:
      file: containers/pg.yaml
      service: postgres
    networks:
      - etl_bridge
    profiles: [infrastracture]
    user: root

  prometheus:
    extends:
      file: containers/prom_grafana.yaml
      service: prometheus
    networks:
      - etl_bridge
    profiles: [monitoring]
    user: root

  grafana:
    extends:
      file: containers/prom_grafana.yaml
      service: grafana
    networks:
      - etl_bridge
    profiles: [monitoring]
    user: root

  scraper:
    image: scraper
    build:
      context: .
      dockerfile: ./scraper/src/Dockerfile
    hostname: scraper
    container_name: scraper
    restart: always
    ports:
      - "${SCRAPER_PORT}:${SCRAPER_PORT}"
    environment:
      - SCRAPER_PORT=$SCRAPER_PORT
    env_file:
      - .env
    networks:
      - etl_bridge
    tty: true
    profiles: [microservice]
    volumes:
      - ./avro:/avro

  shovel:
    image: shovel
    build:
      context: .
      dockerfile: ./shovel/src/Dockerfile
    hostname: shovel
    container_name: shovel
    restart: always
    ports:
      - "${SHOVEL_PORT}:${SHOVEL_PORT}"
    environment:
      - SHOVEL_PORT=$SHOVEL_PORT
    env_file:
      - .env
    networks:
      - etl_bridge
    tty: true
    profiles: [microservice]
    volumes:
      - ./avro:/avro

volumes:
  prom_data: