name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Scraper
      run: docker build --tag scraper:$(date +%s) -f ./scraper/src/Dockerfile .

    - name: Build Shovel
      run: docker build --tag shovel:$(date +%s) -f ./shovel/src/Dockerfile .
